"""Add new fields and file urls to JobSeeker

Revision ID: 90f730487e27
Revises: 2d385c4a1c3c
Create Date: 2026-03-22 21:44:56.113755

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '90f730487e27'
down_revision: Union[str, Sequence[str], None] = '2d385c4a1c3c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('job_seeker_profiles', sa.Column('birth_date', sa.String(), nullable=True))
    op.add_column('job_seeker_profiles', sa.Column('city', sa.String(), nullable=True))
    op.add_column('job_seeker_profiles', sa.Column('district', sa.String(), nullable=True))
    op.add_column('job_seeker_profiles', sa.Column('contact_email', sa.String(), nullable=True))
    op.add_column('job_seeker_profiles', sa.Column('social_links', sa.String(), nullable=True))
    op.add_column('job_seeker_profiles', sa.Column('photo_url', sa.String(), nullable=True))
    op.add_column('job_seeker_profiles', sa.Column('resume_file_url', sa.String(), nullable=True))
    op.drop_column('job_seeker_profiles', 'resume')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('job_seeker_profiles', sa.Column('resume', sa.TEXT(), autoincrement=False, nullable=True))
    op.drop_column('job_seeker_profiles', 'resume_file_url')
    op.drop_column('job_seeker_profiles', 'photo_url')
    op.drop_column('job_seeker_profiles', 'social_links')
    op.drop_column('job_seeker_profiles', 'contact_email')
    op.drop_column('job_seeker_profiles', 'district')
    op.drop_column('job_seeker_profiles', 'city')
    op.drop_column('job_seeker_profiles', 'birth_date')
    # ### end Alembic commands ###
