"""Add ResumeItem table

Revision ID: cae4f01da5cf
Revises: 90f730487e27
Create Date: 2026-03-24 22:46:58.069773

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cae4f01da5cf'
down_revision: Union[str, Sequence[str], None] = '90f730487e27'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('resume_items',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('file_url', sa.String(), nullable=False),
    sa.Column('file_name', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['job_seeker_profiles.user_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_resume_items_id'), 'resume_items', ['id'], unique=False)
    op.drop_column('job_seeker_profiles', 'resume_file_url')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('job_seeker_profiles', sa.Column('resume_file_url', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_index(op.f('ix_resume_items_id'), table_name='resume_items')
    op.drop_table('resume_items')
    # ### end Alembic commands ###
