"""update_vacancy_models

Revision ID: bf050cab5b8e
Revises: 04fd88a93fa5
Create Date: 2026-03-11 20:16:59.569947

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bf050cab5b8e'
down_revision: Union[str, Sequence[str], None] = '04fd88a93fa5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('vacancies', sa.Column('requirements', sa.Text(), nullable=False))
    op.add_column('vacancies', sa.Column('company_id', sa.Integer(), nullable=False))
    op.add_column('vacancies', sa.Column('owner_id', sa.Integer(), nullable=False))
    op.drop_index(op.f('ix_vacancies_employer_id'), table_name='vacancies')
    op.create_index(op.f('ix_vacancies_company_id'), 'vacancies', ['company_id'], unique=False)
    op.drop_column('vacancies', 'employer_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('vacancies', sa.Column('employer_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_index(op.f('ix_vacancies_company_id'), table_name='vacancies')
    op.create_index(op.f('ix_vacancies_employer_id'), 'vacancies', ['employer_id'], unique=False)
    op.drop_column('vacancies', 'owner_id')
    op.drop_column('vacancies', 'company_id')
    op.drop_column('vacancies', 'requirements')
    # ### end Alembic commands ###
